plugins {
    id 'java'
    id "com.gradleup.shadow" version "9.3.1"
}

group = 'me.andromedov'
version = "${version}"

repositories {
    mavenCentral()

    // Paper
    maven { url = 'https://repo.papermc.io/repository/maven-public/' }

    // Skript
    maven { url = 'https://repo.skriptlang.org/releases' }

    // MythicMobs
    maven { url = 'https://mvn.lumine.io/repository/maven-public/' }

    // CodeMC
    maven { url = 'https://repo.codemc.io/repository/maven-public/' }
}

dependencies {
    // Paper API — compileOnly
    compileOnly "io.papermc.paper:paper-api:${paperVersion}"

    // Skript 2.15.2 — compileOnly
    compileOnly "com.github.SkriptLang:Skript:${skriptVersion}"

    // MythicMobs 5.12.0 — compileOnly
    compileOnly "io.lumine:Mythic-Dist:${mythicMobsVersion}"

    // bStats
    implementation "org.bstats:bstats-bukkit:3.2.1"
}

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of("${javaVersion}"))
}

shadowJar {
    relocate 'org.bstats', "${project.group}.mythicskript.bstats"
}

tasks.build {
    dependsOn tasks.shadowJar
}

processResources {
    duplicatesStrategy = DuplicatesStrategy.INCLUDE

    print("Process version....")
    Properties properties = new Properties()
    File file = new File("$project.projectDir/gradle.properties")
    if (file.exists()) {
        properties.load(file.newDataInputStream())
        project.version = properties.version
        println("Done!")
    } else {
        project.version = "1.0.0"
        println("Warning! gradle.properties file is missing!")
    }

    print("Process plugin.yml....")
    inputs.property "version", project.version
    from (sourceSets.main.resources.srcDirs) {
        include "plugin.yml"
        expand "version": project.version
    }

    println("Done!")
}