# --- plugin version ---
build=300
version=1.0.0

# --- dependency versions ---
# For future update, we should choose java 25
# and use "io.papermc.paper:paper-api:26.1.2.build.+"
# but for now it's fine >:)
paperVersion=1.21.11-R0.1-SNAPSHOT
skriptVersion=2.15.2
mythicMobsVersion=5.12.0

javaVersion=21
