name: Dev Build

on:
  push:
    branches:
      - "dev/**"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build_dev:
    if: "!contains(github.event.head_commit.message, '[release]') && !contains(github.event.head_commit.message, '[pre-release]') && !contains(github.event.head_commit.message, '[ci skip]')"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate Gradle wrapper
        uses: gradle/actions/wrapper-validation@v5

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Generate Short SHA
        id: vars
        run: echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get plugin version
        id: version
        run: |
          RAW_VERSION=$(grep '^version=' gradle.properties | cut -d'=' -f2)
          CLEAN_VERSION="${RAW_VERSION%-SNAPSHOT}"
          echo "VERSION=$CLEAN_VERSION" >> $GITHUB_OUTPUT

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build --no-daemon

      - name: Rename Artifact with SNAPSHOT and Hash
        id: rename
        run: |
          cd build/libs
          for file in *.jar; do
            if [[ "$file" != *"-plain.jar"* && "$file" != *"-sources.jar"* && "$file" != *"-javadoc.jar"* ]]; then

              BASENAME="${file%.jar}"
              BASENAME="${BASENAME%-SNAPSHOT}"
              NEW_NAME="${BASENAME}-SNAPSHOT-${{ steps.vars.outputs.SHORT_SHA }}.jar"

              mv "$file" "$NEW_NAME"
              echo "Renamed $file to $NEW_NAME"

              echo "ARTIFACT_FILENAME=$NEW_NAME" >> $GITHUB_ENV
            fi
          done

      - name: Upload Dev Artifact
        uses: actions/upload-artifact@v4
        with:
          name: MythicSkriptAddon-${{ steps.version.outputs.VERSION }}-SNAPSHOT-${{ steps.vars.outputs.SHORT_SHA }}
          path: build/libs/${{ env.ARTIFACT_FILENAME }}
          retention-days: 7